import { MenuItem, Category } from './firestore';

export const sampleCategories: Category[] = [
  { id: 'cat1', name: 'Starters', subcategories: [] },
  { id: 'cat2', name: 'Main Course', subcategories: [] },
  { id: 'cat3', name: 'Biryani', subcategories: [] },
  { id: 'cat4', name: 'Desserts', subcategories: [] },
  { id: 'cat5', name: 'Beverages', subcategories: [] },
];

export const sampleMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Paneer Tikka',
    description: 'Marinated cottage cheese grilled with vegetables and spices',
    price: 250,
    halfPortionCost: 150,
    hasHalfPortion: true,
    isVegetarian: true,
    categoryId: 'cat1',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: ['Dairy'],
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Chicken 65',
    description: 'Spicy deep-fried chicken with aromatic spices',
    price: 280,
    halfPortionCost: 180,
    hasHalfPortion: true,
    isVegetarian: false,
    categoryId: 'cat1',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: [],
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Butter Chicken',
    description: 'Tender chicken in creamy tomato-based curry with butter',
    price: 320,
    halfPortionCost: 200,
    hasHalfPortion: true,
    isVegetarian: false,
    categoryId: 'cat2',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: ['Dairy'],
    imageUrl: 'https://images.unsplash.com/photo-1603894584663-8c5a1b9b4d2a?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Paneer Butter Masala',
    description: 'Cottage cheese cubes in rich, creamy tomato gravy',
    price: 280,
    halfPortionCost: 180,
    hasHalfPortion: true,
    isVegetarian: true,
    categoryId: 'cat2',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: ['Dairy'],
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'Hyderabadi Biryani',
    description: 'Fragrant basmati rice with spiced meat and aromatic herbs',
    price: 350,
    halfPortionCost: 220,
    hasHalfPortion: true,
    isVegetarian: false,
    categoryId: 'cat3',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: [],
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d27a?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Veg Biryani',
    description: 'Mixed vegetables and basmati rice with aromatic spices',
    price: 280,
    halfPortionCost: 180,
    hasHalfPortion: true,
    isVegetarian: true,
    categoryId: 'cat3',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: [],
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '7',
    name: 'Gulab Jamun',
    description: 'Soft milk solids dumplings soaked in rose-flavored sugar syrup',
    price: 120,
    halfPortionCost: 80,
    hasHalfPortion: true,
    isVegetarian: true,
    categoryId: 'cat4',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: ['Dairy', 'Gluten'],
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '8',
    name: 'Mango Lassi',
    description: 'Refreshing yogurt drink with mango pulp and cardamom',
    price: 80,
    halfPortionCost: 50,
    hasHalfPortion: true,
    isVegetarian: true,
    categoryId: 'cat5',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: ['Dairy'],
    imageUrl: 'https://images.unsplash.com/photo-1526424382096-74a93e105682?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '9',
    name: 'Egg Curry',
    description: 'Hard-boiled eggs in spicy onion-tomato gravy',
    price: 180,
    halfPortionCost: 120,
    hasHalfPortion: true,
    isVegetarian: false,
    categoryId: 'cat2',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: ['Eggs'],
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
  {
    id: '10',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe filled with spiced potato mixture',
    price: 150,
    halfPortionCost: 100,
    hasHalfPortion: true,
    isVegetarian: true,
    categoryId: 'cat1',
    franchiseId: 'dcjQSyneEVotjl9dQwFA',
    allergens: ['Gluten'],
    imageUrl: 'https://images.unsplash.com/photo-1589301768045-3a693d5d6b8b?w=300&h=300&fit=crop',
    createdAt: new Date(),
  },
];